apiVersion: batch/v1
kind: Job
metadata:
  name: census-2024-tract-convert
  labels:
    k8s-app: census-2024-tract-convert
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 10800
  template:
    metadata:
      labels:
        k8s-app: census-2024-tract-convert
    spec:
      priorityClassName: opportunistic
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: NotIn
                values:
                - 'true'
      restartPolicy: Never
      containers:
      - name: convert-task
        image: ghcr.io/boettiger-lab/datasets:latest
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: rook-ceph-rgw-nautiluss3.rook
        - name: AWS_PUBLIC_ENDPOINT
          value: s3-west.nrp-nautilus.io
        - name: AWS_HTTPS
          value: 'false'
        - name: AWS_VIRTUAL_HOSTING
          value: 'FALSE'
        - name: BUCKET
          value: public-census
        volumeMounts:
        - name: rclone-config
          mountPath: /root/.config/rclone
          readOnly: true
        command:
        - bash
        - -c
        - |
          set -e
          cng-convert-to-parquet \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_01_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_02_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_04_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_05_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_06_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_08_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_09_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_10_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_11_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_12_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_13_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_15_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_16_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_17_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_18_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_19_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_20_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_21_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_22_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_23_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_24_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_25_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_26_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_27_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_28_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_29_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_30_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_31_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_32_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_33_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_34_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_35_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_36_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_37_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_38_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_39_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_40_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_41_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_42_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_44_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_45_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_46_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_47_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_48_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_49_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_50_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_51_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_53_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_54_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_55_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_56_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_60_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_66_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_69_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_72_tract.zip \
            /vsizip//vsicurl/https://www2.census.gov/geo/tiger/TIGER2024/TRACT/tl_2024_78_tract.zip \
            s3://public-census/census-2024/tract.parquet \
            --row-group-size 100000
        resources:
          requests:
            cpu: '4'
            memory: 16Gi
          limits:
            cpu: '4'
            memory: 16Gi
      volumes:
      - name: rclone-config
        secret:
          secretName: rclone-config
